# Pins
STEP_PIN = 12
DIR_PIN = 13
ENABLE_PIN = None
# BUTTON_PIN = 13
DMX_RX_PIN = 15
DMX_RX_ENABLE_PIN = 16  # active low
DMX_TX_PIN = 18
DMX_TX_ENABLE_PIN = 17  # active high


# button
BUTTON_DEBOUNCE_MS = 200


# motor
STEPS_REV = 200
MICROSTEPS = 16  # 1 if none
INVERT_DIR = False
GEARBOX_MODIFIER = 3
MICROSTEPS_REV = STEPS_REV * MICROSTEPS
SPEED_SPS = MICROSTEPS_REV / 2

# network
WIFI_TIMEOUT_SECONDS = 20
PORT = "COM8"
DMX_BAUDRATE = 250000
BREAK_BAUDRATE = 9600
FRAME_DELAY_S = 0.015  # matches FRAME_DELAY_MS in dmx_demo.py
